name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Debug Directory
      run: |
        pwd
        ls -al

    - name: Install Grunt CLI
      run: npm install -g grunt-cli

    - name: Install Dependencies
      run: npm install || npm ci

    - name: Build
      run: grunt
